apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
  namespace: speedtest
spec:
  replicas: 1 # Puedes ajustar esto si no necesitas una instancia por nodo inicialmente
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:latest
          ports:
            - containerPort: 80 # La aplicación expone en el puerto 80
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: APP_KEY
              value: "base64:13p3VWmxH2gghqI+69y9lmj8eEfRiC7WzliAdZ6+06c="
            - name: DB_CONNECTION
              value: "sqlite"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: speedtest-tracker-config-pvc # Asegúrate de crear este PVC
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker-service
  namespace: speedtest
spec:
  type: ClusterIP # Para acceso interno dentro del clúster
  ports:
    - port: 8080 # El puerto al que accederán otros servicios dentro del clúster
      targetPort: 80 # El puerto en el contenedor
  selector:
    app: speedtest-tracker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-config-pvc
  namespace: speedtest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Ajusta el tamaño según tus necesidades