apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:latest
          ports:
            - containerPort: 80  # The container actually listens on port 80
            - containerPort: 8088  # Optional: keep if needed for other services
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: APP_KEY
              value: # You can generate a key at https://speedtest-tracker.dev
            - name: DISPLAY_TIMEZONE
              value: UTC
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: speedtest_tracker
            - name: DB_USERNAME
              value: speedy
            - name: DB_PASSWORD
              value: password
            - name: SPEEDTEST_SCHEDULE
              value:
            - name: SPEEDTEST_SERVERS
              value:

          volumeMounts:
            - mountPath: /config
              name: speedtest-tracker
      volumes:
        - name: speedtest-tracker
          persistentVolumeClaim:
            claimName: speedtest-tracker

---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: alt
      port: 8088
      targetPort: 8088
  selector:
    app: speedtest-tracker
  type: ClusterIP  # Changed from ClusterIP to expose externally