apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: APP_KEY
              value: "base64:13p3VWmxH2gghqI+69y9lmj8eEfRiC7WzliAdZ6+06c="
            - name: DB_CONNECTION
              value: "sqlite"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: speedtest-tracker-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker-service
spec:
  selector:
    app: speedtest-tracker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: http
    - protocol: TCP
      port: 8443
      targetPort: 443
      name: https
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Ajusta el tamaño según tus necesidades