apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: speedtest-tracker
  name: speedtest-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: speedtest-tracker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: speedtest-tracker
    spec:
      containers:
        - env:
            - name: APP_KEY
              value: base64:13p3VWmxH2gghqI+69y9lmj8eEfRiC7WzliAdZ6+06c=
            - name: DB_CONNECTION
              value: sqlite
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: lscr.io/linuxserver/speedtest-tracker:latest
          name: speedtest-tracker
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: speedtest-tracker-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: speedtest-tracker-cm0
          name: speedtest-tracker-cm0
