apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker-master
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker-master
  template:
    metadata:
      labels:
        app: speedtest-tracker-master
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: server-docker
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:latest
          envFrom:
            - secretRef:
                name: speedtest-tracker-master-secrets
          ports:
            - containerPort: 8088
          volumeMounts:
            - mountPath: /config
              name: speedtest-tracker
      volumes:
        - name: speedtest-tracker
          persistentVolumeClaim:
            claimName: speedtest-tracker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker-axion
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker-axion
  template:
    metadata:
      labels:
        app: speedtest-tracker-axion
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: docker-server-axion
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:latest
          envFrom:
            - secretRef:
                name: speedtest-tracker-axion-secrets
          ports:
            - containerPort: 8088
          volumeMounts:
            - mountPath: /config
              name: speedtest-tracker
      volumes:
        - name: speedtest-tracker
          persistentVolumeClaim:
            claimName: speedtest-tracker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker-alamos
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker-alamos
  template:
    metadata:
      labels:
        app: speedtest-tracker-alamos
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: docker-server-alamos
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:latest
          envFrom:
            - secretRef:
                name: speedtest-tracker-alamos-secrets
          ports:
            - containerPort: 8088
          volumeMounts:
            - mountPath: /config
              name: speedtest-tracker
      volumes:
        - name: speedtest-tracker
          persistentVolumeClaim:
            claimName: speedtest-tracker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker-ypf
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker-ypf
  template:
    metadata:
      labels:
        app: speedtest-tracker-ypf
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: docker-server-ypf
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:latest
          envFrom:
            - secretRef:
                name: speedtest-tracker-ypf-secrets
          ports:
            - containerPort: 8088
          volumeMounts:
            - mountPath: /config
              name: speedtest-tracker
      volumes:
        - name: speedtest-tracker
          persistentVolumeClaim:
            claimName: speedtest-tracker