apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker-master
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker-master
  template:
    metadata:
      labels:
        app: speedtest-tracker-master
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: server-docker
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:latest
          ports:
            - containerPort: 80 # La aplicación expone en el puerto 80
              hostPort: 8080 # Mapeamos el puerto 80 del contenedor al 8080 del host
            - containerPort: 443 # La aplicación expone en el puerto 443 (HTTPS)
              hostPort: 8443 # Mapeamos el puerto 443 del contenedor al 8443 del host
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: APP_KEY
              value: "base64:13p3VWmxH2gghqI+69y9lmj8eEfRiC7WzliAdZ6+06c="
            - name: DB_CONNECTION
              value: "sqlite"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          hostPath:
            path: /opt/speedtest-tracker/config/master
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker-master
  namespace: speedtest
spec:
  type: ClusterIP
  ports:
    - port: 8080 # Puerto del servicio dentro del clúster (coincide con el hostPort HTTP)
      targetPort: 80 # Dirige al containerPort HTTP de la aplicación
    - port: 8443 # Puerto del servicio dentro del clúster (coincide con el hostPort HTTPS)
      targetPort: 443 # Dirige al containerPort HTTPS de la aplicación
  selector:
    app: speedtest-tracker-master