apiVersion: v1
kind: Secret
metadata:
  name: speedtest-tracker-master-secrets
  namespace: myapp
type: Opaque
stringData:
  PUID: "1000"
  PGID: "1000"
  APP_KEY: "your-generated-key"
  DISPLAY_TIMEZONE: "UTC"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_DATABASE: "speedtest_tracker"
  DB_USERNAME: "speedy"
  DB_PASSWORD: "password"
  SPEEDTEST_SCHEDULE: ""
  SPEEDTEST_SERVERS: ""